version: '2'

services:
  nginx:
    image: nginx:latest
    depends_on: 
      - php
      - mysql
    volumes:
      - ./web:/var/www/html
      - ./nginx/sites-enabled/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - appdata:ro
    ports: 
      - "8880:80"
      - "443:443"

  php:
    build:
      context: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    volumes_from:
      - appdata
    env_file: .env
    depends_on:
      - appdata
      - mysql
    user: www-data

  appdata:
    image: alpine:latest
    volumes:
      - ./appdata/startup.sh:/startup.sh
      - ./web:/var/www/html
    command: /bin/sh /startup.sh

  mysql:
    image: mysql:5.7
    env_file: .env
    volumes: 
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306

  java:
    image: java:8
    volumes: 
      - ./java/mahout:/java
    command: ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "java/target/mahoutRecommender-jar-with-dependencies.jar"]

