/var/www/html/bin/magento module:disable Magento_Weee   \
Magento_WebapiSecurity  \
Magento_Version  \
Magento_Usps  \
Magento_Ups  \
Magento_TaxImportExport  \
Magento_SwatchesLayeredNavigation  \
Magento_Swagger  \
Magento_Sitemap  \
Magento_SendFriend  \
Magento_SalesInventory  \
Magento_ProductVideo  \
Magento_Persistent  \
Magento_OfflinePayments  \
Magento_NewRelicReporting  \
Magento_Multishipping  \
Magento_LayeredNavigation  \
Magento_GroupedImportExport  \
Magento_GoogleOptimizer  \
Magento_GoogleAdwords  \
Magento_Fedex  \
Magento_EncryptionKey  \
Magento_DownloadableImportExport  \
Magento_Dhl  \
Magento_Deploy  \
Magento_CustomerImportExport  \
Magento_CurrencySymbol  \
Magento_ConfigurableImportExport  \
Magento_CheckoutAgreements  \
Magento_CatalogWidget  \
Magento_CatalogRuleConfigurable  \
Magento_Captcha  \
Magento_CacheInvalidate  \
Magento_BundleImportExport  \
Magento_Braintree  \
Magento_Authorizenet  \
Magento_AdvancedPricingImportExport  \
Magento_AdminNotification  \
Magento_Marketplace  \
Magento_BundleSampleData  \
Magento_SalesRuleSampleData  \
Magento_SalesSampleData  \
Magento_CustomerSampleData  \
Magento_CmsSampleData  \
Magento_TaxSampleData  \
Magento_GroupedProductSampleData  \
Magento_DownloadableSampleData  \
Magento_WidgetSampleData  \
Magento_MsrpSampleData  \
Magento_WishlistSampleData  \
Magento_ReviewSampleData  \
Magento_SwatchesSampleData  \
Magento_OfflineShippingSampleData  \
AvS_DisableModules  \
